name: Send and Reply Tweet Action
description: Post or reply to a tweet to Twitter during a GitHub Actions workflow.
author: Ric Wood
inputs:
  status:
    description: The status ("tweet") to post to twitter.
  replyto:
    description: Optional status ID of tweet to post a reply to.
  consumer-key:
    description: >
      Consumer API key, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
  consumer-secret:
    description: >
      Consumer API secret key, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
  access-token:
    description: >
      Application access token, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
  access-token-secret:
    description: >
      Application access token secret, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.
runs:
  using: node20
  main: dist/index.js
branding:
  icon: edit
  color: blue
